/**
 * @file
 *	Honestly, I don't really know what this is yet.
 *	This could potentially be completed removed and just
 *	integrated as a part of a GameWorld class.
 *
 * @author  George Kudrayvtsev
 * @version 0.1
 *
 * @addtogroup Game
 */
/// @{

#ifndef GAME_EVENT_HANDLER_H
#define GAME_EVENT_HANDLER_H

namespace game
{
    /// Handles game events generated by engine sub-systems.
    class CL_EventHandler
    {
    public:
        CL_EventHandler();
        ~CL_EventHandler();
    };
}

#endif // GAME_EVENT_HANDLER_H

/// @}