/**
 * @file
 *	Declarations for the GameEvent structure.
 *
 * @author  George Kudrayvtsev
 * @version 0.9.0
 *
 * @addtogroup Game
 */
/// @{

#ifndef GAME_EVENT_H
#define GAME_EVENT_H

#include "Assets/Entity.h"

namespace game
{
    /// Various events that must be handled in the game.
    enum CL_GameEventType
    {
        e_NONE = 0,
        e_MOVE_ENTITY
    };

    /// The event structure generated by various engine sub-systems.
    struct CL_GameEvent
    {
        CL_GameEventType    type;
        asset::GL_Entity*   p_Entity;
        math::ML_Vector2*   p_Vector;
    };
}

#endif // GAME_EVENT_H

/// @}